POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Artem Mozarella",
    "number": "002-444-444"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "anyitem": "123-123-123"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Artem Nedostup"
}